; PlatformIO Project Configuration File
; ESP32-S3 ePaper 1.54 LVGL Step 1

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; 串口监控
monitor_speed = 115200

; 构建标志
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; 库依赖
lib_deps = 
    lvgl/lvgl@^8.3.0

; Flash 大小
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

; PSRAM 支持
board_build.psram_type = opi
board_has_psram = true
